### ISSUE TITLE
Add links field

### ISSUE THREAD

**Issue by silvenon** [twin/waldorfcamp-api#1]
According to [JSON API](http://jsonapi.org/):

``` js
  "links": {
    "self": "http://example.com/posts",
    "next": "http://example.com/posts?page[offset]=2",
    "last": "http://example.com/posts?page[offset]=10"
  },
```

And you thought you could get away with it.

P.S. Not sure what `[offset]` is, though.

**Comment by janko** [comment]
I first considered adding this, but it requires suprisingly much code, so I thought that you could just go through pages until you get an empty result. Would that be feasible?

**Comment by silvenon** [comment]
Yeah.
