### ISSUE TITLE
Deployati na DigitalOcean

### ISSUE THREAD

**Issue by janko** [twin/waldorfcamp-api#3]
Heroku je previše nepouzdan, i 30 sekundi je preveliki delay kad se uspava, pa treba deployati na pravi server.

**Comment by silvenon** [comment]
Get on with it, chop chop.

:stuck_out_tongue:

**Comment by janko** [comment]
Done!

```
curl "46.101.129.78/photos?page=1&perPage=10"
```

**Comment by silvenon** [comment]
:-1:
:honey_pot:
